#!/usr/bin/env python3
"""
build_question_field_states.py — compute a structured field state for each
active tracked question.

Phase D: introduces an explicit per-question field layer. The output of this
script becomes the single structured intermediate that briefs (Phase B) and
triggers (Phase C) both consume.

Flow:
  topicspace data  →  question context (cohort)  →  question_field_state
                                                    ↓             ↓
                                                  brief         triggers

The field state is computed deterministically from actors.json + backtest
history. It is NOT generated by the model. Natural-language summaries embedded
in the state are templated from the structural facts.

Output:
  data/derived/question_field_states.json     # latest, keyed by question_id

Re-running on the same day preserves the prior_summary so we don't lose the
"what changed?" comparison point. Running on a new date pushes the previous
state into prior_summary.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

REPO_ROOT      = Path(__file__).resolve().parent.parent
SITE_ROOT      = REPO_ROOT.parent / "topicspace-site"
GRAPH_FILE     = REPO_ROOT / "data" / "derived" / "question_graph.json"
ACTORS_FILE    = SITE_ROOT / "public" / "actors.json"
HISTORY_FILE   = REPO_ROOT / "data" / "derived" / "backtest_history.parquet"
STATES_FILE    = REPO_ROOT / "data" / "derived" / "question_field_states.json"

LOOKBACK_DAYS  = 5

# ── Read-class taxonomy ──────────────────────────────────────────────────────
# Shared with generate_derived_questions.py. Kept here to avoid a hard import
# dependency; if these diverge, both should be updated.

READ_CLASS = {
    "price confirming narrative":         "bullish_confirming",
    "price starting to follow":           "bullish_early",
    "early confirmation forming":         "bullish_early",
    "price rejecting negative narrative": "bullish_rejecting",
    "story not being paid":               "divergence_unpaid",
    "price ahead of story":               "price_led",
    "selloff confirming narrative":       "bearish_confirming",
    "price confirming negative story":    "bearish_confirming",
    "price lagging narrative":            "lagging",
    "no follow-through":                  "no_follow",
    "moving with tape":                   "macro",
}

READ_DIRECTION = {
    "bullish_confirming":  "bullish",
    "bullish_early":       "bullish",
    "bullish_rejecting":   "bullish",
    "divergence_unpaid":   "neutral",   # narrative-price tension
    "price_led":           "bullish",
    "bearish_confirming":  "bearish",
    "lagging":             "neutral",
    "no_follow":           "neutral",
    "macro":               "neutral",
}

READ_CLASS_LABEL = {
    "bullish_confirming":  "follow-through",
    "bullish_early":       "early follow-through",
    "bullish_rejecting":   "bearish-rejection",
    "divergence_unpaid":   "story-not-being-paid",
    "price_led":           "price-led",
    "bearish_confirming":  "downside-confirming",
    "lagging":             "lagging",
    "no_follow":           "no-follow-through",
    "macro":               "macro-following",
}

TENSION_CLASSES = {"divergence_unpaid", "bullish_rejecting", "price_led"}

# Ticker → semantic role (kept aligned with generate_derived_questions.py)
TOPIC_LABELS = {
    "VST":  "power-adjacent", "CEG":  "power-adjacent", "VRT":  "power-adjacent",
    "NVDA": "chip", "AMD":  "chip", "INTC": "chip", "ARM":  "chip",
    "AVGO": "chip", "MU":   "chip", "MRVL": "chip", "TSM":  "chip",
    "ASML": "chip", "COHR": "chip", "ALAB": "chip",
    "WDC":  "storage", "SNDK": "storage",
    "SMCI": "server", "DELL": "server", "CLS":  "server",
    "CRM":  "software", "ADBE": "software", "DDOG": "software", "SNOW": "software",
    "MSFT": "hyperscaler", "AMZN": "hyperscaler", "GOOGL": "hyperscaler",
    "ORCL": "hyperscaler", "META": "platform",
    "CRWV": "neocloud", "NBIS": "neocloud",
    "ANET": "networking",
    "AAPL": "consumer-tech", "NFLX": "consumer-tech",
    "TSLA": "ev", "PLTR": "ai-platform",
    "TTD":  "ad-tech", "ZETA": "ad-tech",
    "MELI": "ecommerce-fintech", "SOFI": "fintech",
}

DOMINANT_LABEL_THRESHOLD = 0.50    # ≥ 50% share → assign that label
COHESION_FRAGMENTED_MAX  = 0.33    # if no class > 33%, cohort is fragmented
COHESION_COHERENT_MIN    = 0.66    # ≥ 66% in one class → coherent
COHORT_MIN_GROUP_SIZE    = 3       # threshold for "real" sub-cohort


# ─────────────────────────────────────────────────────────────────────────────
# I/O
# ─────────────────────────────────────────────────────────────────────────────

def load_json(path: Path, default=None):
    if not path.exists():
        if default is not None:
            return default
        sys.exit(f"missing: {path}")
    return json.loads(path.read_text())


def save_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=False) + "\n")


def load_snapshot() -> dict:
    data = load_json(ACTORS_FILE)
    return {a["t"]: a for a in data.get("actors", [])}


def load_history():
    if not HISTORY_FILE.exists():
        return None
    try:
        import pandas as pd
    except ImportError:
        return None
    df = pd.read_parquet(HISTORY_FILE)
    if not {"date", "ticker", "state"}.issubset(df.columns):
        return None
    df = df.sort_values("date")
    out: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for row in df.itertuples(index=False):
        out[row.ticker].append((str(row.date), str(row.state)))
    return out


def historical_state(history, ticker: str, lookback_days: int) -> str | None:
    if not history or ticker not in history:
        return None
    rows = history[ticker]
    if not rows:
        return None
    if len(rows) <= lookback_days:
        return rows[0][1]
    return rows[-1 - lookback_days][1]


def state_to_class(state: str) -> str:
    return {
        "CONFIRMED":        "bullish_confirming",
        "EARLY":            "bullish_early",
        "DISAGREEMENT":     "bullish_rejecting",
        "DIVERGENCE":       "divergence_unpaid",
        "PRICE-LED":        "price_led",
        "NEG_CONFIRMATION": "bearish_confirming",
        "REPRICING":        "lagging",
        "UNCLEAR":          "no_follow",
        "MACRO":            "macro",
    }.get(state, "no_follow")


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def cohort_label(tickers: list[str]) -> str:
    """Dominant topic label for a sub-cohort, else 'mixed'."""
    if not tickers:
        return "mixed"
    labels = [TOPIC_LABELS.get(t, "other") for t in tickers]
    counts = Counter(labels)
    top, n = counts.most_common(1)[0]
    if top != "other" and n / len(tickers) >= DOMINANT_LABEL_THRESHOLD:
        return top
    return "mixed"


def cohesion_label(largest_share: float) -> str:
    if largest_share >= COHESION_COHERENT_MIN:
        return "coherent"
    if largest_share <= COHESION_FRAGMENTED_MAX:
        return "fragmented"
    return "mixed"


# ─────────────────────────────────────────────────────────────────────────────
# Core: compute one question field state
# ─────────────────────────────────────────────────────────────────────────────

def compute_state(
    question: dict,
    snapshot: dict,
    history,
    prior_state: dict | None,
    as_of: str,
) -> dict:
    cohort = question.get("cohort") or question.get("entities") or []

    # ── current snapshot for cohort ─────────────────────────────────────────
    by_class: dict[str, list[str]] = defaultdict(list)
    by_sector: dict[str, list[str]] = defaultdict(list)
    in_snapshot: list[str] = []
    actor_states: dict[str, str] = {}   # ticker → current state

    for t in cohort:
        a = snapshot.get(t)
        if a is None:
            continue
        in_snapshot.append(t)
        cls = READ_CLASS.get(a.get("read", ""))
        if cls:
            by_class[cls].append(t)
        sector = a.get("sector", "Unknown")
        by_sector[sector].append(t)
        actor_states[t] = a.get("state", "")

    # ── prior state (LOOKBACK_DAYS ago) for each cohort member ──────────────
    prior_class_by_actor: dict[str, str] = {}
    if history:
        for t in in_snapshot:
            hist_state = historical_state(history, t, LOOKBACK_DAYS)
            if hist_state:
                prior_class_by_actor[t] = state_to_class(hist_state)

    # ── split patterns ──────────────────────────────────────────────────────
    split_patterns = []
    for cls, members in sorted(by_class.items(), key=lambda kv: -len(kv[1])):
        if len(members) < COHORT_MIN_GROUP_SIZE:
            continue
        split_patterns.append({
            "class":   cls,
            "label":   cohort_label(members),
            "members": sorted(members),
            "n":       len(members),
            "read_class_label": READ_CLASS_LABEL.get(cls, cls),
        })

    # ── emerging / repeating / conflicting ─────────────────────────────────
    emerging = []
    repeating = []
    for group in split_patterns:
        members = group["members"]
        cls = group["class"]
        if not prior_class_by_actor:
            continue
        prior_same = [m for m in members if prior_class_by_actor.get(m) == cls]
        prior_other = [m for m in members if m in prior_class_by_actor and prior_class_by_actor[m] != cls]
        share_same = len(prior_same) / len(members) if members else 0
        if share_same < 0.5:
            emerging.append({
                "label":               group["label"],
                "class":               cls,
                "read_class_label":    group["read_class_label"],
                "members_persistent":  sorted(prior_same),
                "members_new":         sorted(prior_other),
                "summary":             (
                    f"{group['read_class_label']} cohort ({group['label']}): "
                    f"{', '.join(sorted(prior_other) or members)} rotated into this read recently."
                ),
            })
        elif share_same >= 0.66:
            repeating.append({
                "label":            group["label"],
                "class":            cls,
                "read_class_label": group["read_class_label"],
                "members":          sorted(members),
                "summary":          (
                    f"{group['read_class_label']} cohort ({group['label']}): "
                    f"{', '.join(sorted(members))} unchanged across the lookback window."
                ),
            })

    conflicting = [
        {
            "label":            g["label"],
            "class":            g["class"],
            "read_class_label": g["read_class_label"],
            "members":          g["members"],
            "tension":          "narrative-price disagreement",
        }
        for g in split_patterns
        if g["class"] in TENSION_CLASSES
    ]

    # ── dominant pattern ───────────────────────────────────────────────────
    total_classified = sum(len(v) for v in by_class.values())
    dominant_pattern = None
    if by_class and total_classified:
        top_cls, top_members = max(by_class.items(), key=lambda kv: len(kv[1]))
        top_label = cohort_label(top_members)
        share = len(top_members) / total_classified
        dominant_pattern = {
            "class":            top_cls,
            "read_class_label": READ_CLASS_LABEL.get(top_cls, top_cls),
            "label":            top_label,
            "members":          sorted(top_members),
            "share":            round(share, 3),
            "summary":          (
                f"{READ_CLASS_LABEL.get(top_cls, top_cls)} cohort dominates ({top_label}): "
                f"{', '.join(sorted(top_members))}"
            ) if share >= 0.30 else (
                f"no single read class dominates ({len(by_class)} distinct reads in cohort)"
            ),
        }

    # ── fragmentation / cohesion ───────────────────────────────────────────
    largest_share = max((len(v) for v in by_class.values()), default=0) / total_classified \
        if total_classified else 0
    fragmentation = {
        "n_classes":      len(by_class),
        "largest_share":  round(largest_share, 3),
        "is_fragmented":  largest_share <= COHESION_FRAGMENTED_MAX,
    }
    cohesion = {
        "label":   cohesion_label(largest_share),
        "summary": _cohesion_summary(question, by_class, largest_share, split_patterns),
    }

    # ── novelty signals: actors whose state class changed in last LOOKBACK ──
    novelty_signals = []
    for t in in_snapshot:
        prior_cls = prior_class_by_actor.get(t)
        cur_read = snapshot[t].get("read", "")
        cur_cls  = READ_CLASS.get(cur_read)
        if prior_cls and cur_cls and prior_cls != cur_cls:
            novelty_signals.append({
                "ticker":  t,
                "from":    READ_CLASS_LABEL.get(prior_cls, prior_cls),
                "to":      READ_CLASS_LABEL.get(cur_cls, cur_cls),
                "summary": f"{t} shifted from {READ_CLASS_LABEL.get(prior_cls, prior_cls)} "
                           f"to {READ_CLASS_LABEL.get(cur_cls, cur_cls)}",
            })

    # ── question_pressure ──────────────────────────────────────────────────
    pressure_components = {
        "transitions": len(novelty_signals),                          # 0..N
        "emerging_cohorts": len(emerging),                            # 0..K
        "tension_cohorts":  len(conflicting),                         # 0..K
    }
    pressure = min(100,
                   10 * pressure_components["transitions"] +
                   15 * pressure_components["emerging_cohorts"] +
                   10 * pressure_components["tension_cohorts"])
    question_pressure = {"score": pressure, "components": pressure_components}

    # ── trigger-relevant signals (precomputed shortcuts for Phase C) ───────
    distinct_big_classes = [g for g in split_patterns if g["n"] >= COHORT_MIN_GROUP_SIZE]
    trigger_signals = {
        "cluster_split_ready":  len(distinct_big_classes) >= 2,
        "contradiction_ready":  False,  # only Phase C can decide — depends on prior brief
        "too_broad_ready":      fragmentation["is_fragmented"] and
                                len([g for g in by_class.values() if len(g) >= 2]) >= 3 and
                                len(in_snapshot) >= 6,
        "n_distinct_classes":   len(by_class),
        "n_classes_ge_three":   len(distinct_big_classes),
    }

    # ── change detection vs prior_state ────────────────────────────────────
    prior_summary = _compact_summary(prior_state) if prior_state else None
    change = _diff(prior_state, dominant_pattern, fragmentation, by_class, actor_states)

    return {
        "question_id":           question["question_id"],
        "as_of":                 as_of,
        "cohort":                list(cohort),
        "cohort_in_snapshot":    sorted(in_snapshot),
        "cohort_missing":        sorted(set(cohort) - set(in_snapshot)),
        "by_read_class":         {k: sorted(v) for k, v in by_class.items()},
        "by_sector":             {k: sorted(v) for k, v in by_sector.items()},
        "actor_states":          actor_states,
        "dominant_pattern":      dominant_pattern,
        "split_patterns":        split_patterns,
        "emerging_patterns":     emerging,
        "repeating_patterns":    repeating,
        "conflicting_patterns":  conflicting,
        "fragmentation":         fragmentation,
        "cohesion":              cohesion,
        "novelty_signals":       novelty_signals,
        "question_pressure":     question_pressure,
        "trigger_signals":       trigger_signals,
        "question_confidence":   question.get("confidence"),
        "changed_since_last_run": change["changed"],
        "change_summary":        change["summary"],
        "changed_fields":        change["fields"],
        "actor_set_diff":        change["actor_set_diff"],
        "prior_summary":         prior_summary,
        "lookback_days":         LOOKBACK_DAYS,
    }


def _cohesion_summary(question, by_class, largest_share, split_patterns) -> str:
    if not by_class:
        return "no cohort members found in current snapshot"
    if largest_share >= COHESION_COHERENT_MIN:
        return "cohort behaving as one coherent class"
    if largest_share <= COHESION_FRAGMENTED_MAX:
        return f"cohort fragmented across {len(by_class)} distinct read classes"
    if len(split_patterns) >= 2:
        a, b = split_patterns[0], split_patterns[1]
        return (f"cohort no longer one coherent class — "
                f"{a['read_class_label']} ({a['label']}) and "
                f"{b['read_class_label']} ({b['label']}) both visible")
    return "cohort mixed; no single dominant pattern"


def _compact_summary(state: dict | None) -> dict | None:
    if state is None:
        return None
    return {
        "as_of":             state.get("as_of"),
        "dominant_class":    (state.get("dominant_pattern") or {}).get("class"),
        "largest_share":     (state.get("fragmentation") or {}).get("largest_share"),
        "n_classes":         (state.get("fragmentation") or {}).get("n_classes"),
        "split_n":           len(state.get("split_patterns") or []),
        "emerging_n":        len(state.get("emerging_patterns") or []),
        "pressure":          (state.get("question_pressure") or {}).get("score"),
        "actor_states":      state.get("actor_states") or {},
    }


def _diff(prior: dict | None, dom_now, frag_now, by_class_now, actor_states_now) -> dict:
    if prior is None or prior.get("as_of") == _today_iso():
        return {"changed": False, "summary": "no prior snapshot — first run for this question",
                "fields": [], "actor_set_diff": {"added": [], "removed": []}}

    fields_changed = []
    prior_dom = (prior.get("dominant_pattern") or {}).get("class")
    now_dom   = (dom_now or {}).get("class")
    if prior_dom != now_dom:
        fields_changed.append("dominant_pattern")

    prior_frag = (prior.get("fragmentation") or {}).get("n_classes")
    if prior_frag != frag_now.get("n_classes"):
        fields_changed.append("fragmentation.n_classes")

    prior_states = prior.get("actor_states") or {}
    transitioned = [t for t, s in actor_states_now.items() if prior_states.get(t) not in (None, s)]
    if transitioned:
        fields_changed.append("actor_states")

    added   = sorted(set(actor_states_now) - set(prior_states))
    removed = sorted(set(prior_states) - set(actor_states_now))

    summary_bits = []
    if transitioned:
        sample = ", ".join(sorted(transitioned)[:5])
        more = "" if len(transitioned) <= 5 else f" + {len(transitioned) - 5} more"
        summary_bits.append(f"{len(transitioned)} state transition(s): {sample}{more}")
    if prior_dom != now_dom:
        summary_bits.append(
            f"dominant class shifted {prior_dom or '∅'} → {now_dom or '∅'}"
        )
    if added:
        summary_bits.append(f"new in cohort scope: {', '.join(added)}")
    if removed:
        summary_bits.append(f"left cohort scope: {', '.join(removed)}")

    return {
        "changed":        bool(summary_bits),
        "summary":        "; ".join(summary_bits) or "no material change",
        "fields":         fields_changed,
        "actor_set_diff": {"added": added, "removed": removed},
    }


def _today_iso() -> str:
    return date.today().isoformat()


# ─────────────────────────────────────────────────────────────────────────────
# Driver
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    p = argparse.ArgumentParser(description="compute per-question field state")
    p.add_argument("--only", action="append", default=None,
                   help="restrict to specific question_ids (repeatable)")
    p.add_argument("--include-derived", action="store_true",
                   help="include status=candidate / derived nodes too")
    p.add_argument("--dry-run", action="store_true",
                   help="show what would be written, do not write")
    args = p.parse_args()

    graph     = load_json(GRAPH_FILE)
    snapshot  = load_snapshot()
    history   = load_history()
    existing  = load_json(STATES_FILE, default={"as_of": None, "states": {}})

    today = _today_iso()
    nodes = [n for n in graph["nodes"] if n.get("status") == "active"]
    if args.include_derived:
        nodes = [n for n in graph["nodes"] if n.get("status") in {"active", "candidate"}]
    if args.only:
        wanted = set(args.only)
        nodes = [n for n in nodes if n["question_id"] in wanted]
        missing = wanted - {n["question_id"] for n in nodes}
        if missing:
            sys.exit(f"unknown / non-eligible question_ids: {sorted(missing)}")

    new_states: dict[str, dict] = {}
    for q in nodes:
        qid = q["question_id"]
        prior = existing.get("states", {}).get(qid)
        # If the existing state is from today, keep its prior_summary (don't lose history)
        prior_for_diff = prior
        if prior and prior.get("as_of") == today:
            # carry forward the prior_summary from the existing same-day state
            prior_for_diff = None
        new = compute_state(q, snapshot, history, prior_for_diff, today)
        if prior and prior.get("as_of") == today and prior.get("prior_summary"):
            new["prior_summary"] = prior["prior_summary"]
        new_states[qid] = new

    out = {
        "as_of":   today,
        "states":  new_states,
    }

    print(f"\nquestion field states · {today}")
    print("─" * 76)
    for qid, st in new_states.items():
        dom = st["dominant_pattern"] or {}
        frag = st["fragmentation"]
        coh = st["cohesion"]
        pressure = st["question_pressure"]["score"]
        changed = "Δ" if st["changed_since_last_run"] else "·"
        print(f"  {changed} {qid}  cohesion={coh['label']:11s} "
              f"frag={frag['n_classes']:2d}cls/{frag['largest_share']:.0%}  "
              f"pressure={pressure:3d}  "
              f"dom={dom.get('read_class_label', '—')}")
        if st["changed_since_last_run"]:
            print(f"      Δ: {st['change_summary']}")
        if st["trigger_signals"]["cluster_split_ready"]:
            print(f"      trigger: cluster_split ready ({st['trigger_signals']['n_classes_ge_three']} classes ≥3)")

    if args.dry_run:
        print("\n(dry-run, no writes)")
        return
    save_json(STATES_FILE, out)
    print(f"\nwrote {STATES_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
